---
title: "BIOL7263 - Fall 2022 - Data Wrangling and Visualization for Biology"
author: "Matthew Toomey"
date: "8/9/2022"
output:
  prettydoc::html_pretty:
    theme: Cayman
    highlight: github
---

This site contains course materials for BIOL7263 Data Wrangling and Visualization for Biology, Fall 2022.

## Course Materials

[Scheduling Survey](https://forms.gle/CUaDDMa7enTy3YL59)

[Presentation sign-up sheet](https://docs.google.com/spreadsheets/d/1iSrRPsjxpzHALhK4eL7URGmOxW1vBUWvOam4CoJK8ss/edit?usp=sharing)

[Software Installation](CourseMaterials/InstallationInstructions.html)

[Course Syllabus](CourseMaterials/CourseSyllabus.html)   

___

## Lecture Outlines & Homework Assignments

Date (week of)  | Lecture | Assignments
------------- |----------- | -------------
August 22  | [Class organization and scheduling](https://forms.gle/CUaDDMa7enTy3YL59) | -  
August 29  | [Intro to R](Lectures/Lesson2a.html), RStudio, [Git](Lectures/Lesson2.html) | [Assignment 1](Assignments/Assignment1.html)  
September 5  | [Rmarkdown](Lectures/Lesson3.html) | [Assignment 2](Assignments/Assignment2.html)  
September 12  | [Intro to Regular Expressions](Lectures/Lesson4.html), [dplyr and wrangling](Lectures/Lesson5.html) | TBD  
September 19  | dplyr and wrangling| TBD  
September 26  | ggplot2 | TBD  
October 3  | ggplot2, Inkscape, Gimp | TBD  
October 10  | TBD | TBD  
October 17  | GIS in R | TBD  
October 24  | [Student lessons](https://docs.google.com/spreadsheets/d/1iSrRPsjxpzHALhK4eL7URGmOxW1vBUWvOam4CoJK8ss/edit?usp=sharing) | -
October 31  | [Student lessons](https://docs.google.com/spreadsheets/d/1iSrRPsjxpzHALhK4eL7URGmOxW1vBUWvOam4CoJK8ss/edit?usp=sharing) | -  
November 7  | [Student lessons](https://docs.google.com/spreadsheets/d/1iSrRPsjxpzHALhK4eL7URGmOxW1vBUWvOam4CoJK8ss/edit?usp=sharing) | -  
November 14  | [Student lessons](https://docs.google.com/spreadsheets/d/1iSrRPsjxpzHALhK4eL7URGmOxW1vBUWvOam4CoJK8ss/edit?usp=sharing) | -  
November 21  | Thanksgiving break | -  
November 28  | [Student lessons](https://docs.google.com/spreadsheets/d/1iSrRPsjxpzHALhK4eL7URGmOxW1vBUWvOam4CoJK8ss/edit?usp=sharing) | -  
December 5  | Last day of classes | -  

___

### Important Dates
- 26 August: Last day to add classes through self-service
- 30 August: Last day to add/drop through advising
- 5 September: Labor day
- 11 November: Last day to withdraw
- 21-25 November: Thanksgiving Break
- 5 December: Last day of classes


